In [244]:
import pandas as pd
import numpy as np
import os
import sqlite3
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [245]:
os.path.abspath('.')

'C:\\Users\\silvi\\onedrive\\documentos\\ironhack\\ih_datamadpt1121_project_m3\\data'

In [246]:
os.listdir("./")

['.ipynb_checkpoints',
 'diamonds.csv',
 'diamonds.sqlite',
 'Diamondssql.csv',
 'diamonds_test.csv',
 'diamonds_train.db',
 'sample_submission.csv',
 'Untitled.ipynb']

In [247]:
train = pd.read_csv('C:\\Users\\silvi\\onedrive\\documentos\\ironhack\\ih_datamadpt1121_project_m3\\data\\Diamondssql.csv')
test = pd.read_csv('C:\\Users\\silvi\\onedrive\\documentos\\ironhack\\ih_datamadpt1121_project_m3\\data\\diamonds_test.csv')
sample_sub = pd.read_csv('C:\\Users\\silvi\\onedrive\\documentos\\ironhack\\ih_datamadpt1121_project_m3\\data\\sample_submission.csv')

In [248]:
train

color        cut clarity  price       city  depth  carat  table     x  \
0         J    Premium     VS2   4268      Dubai   62.4   1.21   58.0  6.83   
1         H  Very Good     VS2    505   Kimberly   63.0   0.32   57.0  4.35   
2         G       Fair     VS1   2686  Las Vegas   65.5   0.71   55.0  5.62   
3         D       Good     SI1    738   Kimberly   63.8   0.41   56.0  4.68   
4         G      Ideal     SI1   4882      Dubai   60.5   1.02   59.0  6.55   
...     ...        ...     ...    ...        ...    ...    ...    ...   ...   
40450     G      Ideal     VS1  10070    Antwerp   62.7   1.34   57.0  7.10   
40451     F       Good     SI2  12615     Madrid   57.1   2.02   60.0  8.31   
40452     H      Ideal     SI1   5457   Kimberly   62.7   1.01   56.0  6.37   
40453     J      Ideal     VS1    456   Kimberly   61.9   0.33   54.3  4.45   
40454     I      Ideal     SI1   6232     London   62.0   1.24   58.0  6.83   

          y     z  
0      6.79  4.25  
1      4.38  2.75  
2      5.53  3.65  
3      4.72  3.00  
4      6.51  3.95  
...     ...   ...  
40450  7.04  4.43  
40451  8.25  4.73  
40452  6.42  4.01  
40453  4.47  2.76  
40454  6.88  4.25  

[40455 rows x 11 columns]

In [249]:
train.columns

Index(['color', 'cut', 'clarity', 'price', 'city', 'depth', 'carat', 'table',
       'x', 'y', 'z'],
      dtype='object')

In [254]:
#Training set

target = 'price'

train_dataframe = pd.get_dummies(train)
train_dataframe

price  depth  carat  table     x     y     z  color_D  color_E  \
0       4268   62.4   1.21   58.0  6.83  6.79  4.25        0        0   
1        505   63.0   0.32   57.0  4.35  4.38  2.75        0        0   
2       2686   65.5   0.71   55.0  5.62  5.53  3.65        0        0   
3        738   63.8   0.41   56.0  4.68  4.72  3.00        1        0   
4       4882   60.5   1.02   59.0  6.55  6.51  3.95        0        0   
...      ...    ...    ...    ...   ...   ...   ...      ...      ...   
40450  10070   62.7   1.34   57.0  7.10  7.04  4.43        0        0   
40451  12615   57.1   2.02   60.0  8.31  8.25  4.73        0        0   
40452   5457   62.7   1.01   56.0  6.37  6.42  4.01        0        0   
40453    456   61.9   0.33   54.3  4.45  4.47  2.76        0        0   
40454   6232   62.0   1.24   58.0  6.83  6.88  4.25        0        0   

       color_F  ...  city_Kimberly  city_Las Vegas  city_London  \
0            0  ...              0               0            0   
1            0  ...              1               0            0   
2            0  ...              0               1            0   
3            0  ...              1               0            0   
4            0  ...              0               0            0   
...        ...  ...            ...             ...          ...   
40450        0  ...              0               0            0   
40451        1  ...              0               0            0   
40452        0  ...              1               0            0   
40453        0  ...              1               0            0   
40454        0  ...              0               0            1   

       city_Luxembourg  city_Madrid  city_New York City  city_Paris  \
0                    0            0                   0           0   
1                    0            0                   0           0   
2                    0            0                   0           0   
3                    0            0                   0           0   
4                    0            0                   0           0   
...                ...          ...                 ...         ...   
40450                0            0                   0           0   
40451                0            1                   0           0   
40452                0            0                   0           0   
40453                0            0                   0           0   
40454                0            0                   0           0   

       city_Surat  city_Tel Aviv  city_Zurich  
0               0              0            0  
1               0              0            0  
2               0              0            0  
3               0              0            0  
4               0              0            0  
...           ...            ...          ...  
40450           0              0            0  
40451           0              0            0  
40452           0              0            0  
40453           0              0            0  
40454           0              0            0  

[40455 rows x 40 columns]

In [255]:
test_df = pd.get_dummies(test)
test_df

id  carat  depth  table     x     y     z  cut_Fair  cut_Good  \
0          0   0.79   62.7   60.0  5.82  5.89  3.67         0         0   
1          1   1.20   61.0   57.0  6.81  6.89  4.18         0         0   
2          2   1.57   62.2   61.0  7.38  7.32  4.57         0         0   
3          3   0.90   63.8   54.0  6.09  6.13  3.90         0         0   
4          4   0.50   62.9   58.0  5.05  5.09  3.19         0         0   
...      ...    ...    ...    ...   ...   ...   ...       ...       ...   
13480  13480   0.57   61.9   56.0  5.35  5.32  3.30         0         0   
13481  13481   0.71   62.2   55.0  5.71  5.73  3.56         0         0   
13482  13482   0.70   61.6   55.0  5.75  5.71  3.53         0         0   
13483  13483   0.70   58.8   57.0  5.85  5.89  3.45         0         0   
13484  13484   0.40   62.4   55.0  4.70  4.73  2.94         0         0   

       cut_Ideal  ...  city_Kimberly  city_Las Vegas  city_London  \
0              0  ...              0               0            0   
1              1  ...              0               0            0   
2              0  ...              1               0            0   
3              0  ...              1               0            0   
4              0  ...              0               0            0   
...          ...  ...            ...             ...          ...   
13480          1  ...              0               0            0   
13481          1  ...              0               0            0   
13482          1  ...              0               0            0   
13483          0  ...              0               0            0   
13484          1  ...              0               0            0   

       city_Luxembourg  city_Madrid  city_New York City  city_Paris  \
0                    0            0                   0           0   
1                    0            0                   0           0   
2                    0            0                   0           0   
3                    0            0                   0           0   
4                    0            0                   0           0   
...                ...          ...                 ...         ...   
13480                0            0                   0           0   
13481                0            0                   1           0   
13482                0            0                   0           0   
13483                0            0                   0           0   
13484                0            0                   1           0   

       city_Surat  city_Tel Aviv  city_Zurich  
0               0              0            0  
1               1              0            0  
2               0              0            0  
3               0              0            0  
4               0              0            0  
...           ...            ...          ...  
13480           0              0            0  
13481           0              0            0  
13482           0              1            0  
13483           1              0            0  
13484           0              0            0  

[13485 rows x 40 columns]

In [256]:
train_df = train_dataframe.drop('price', axis=1)
train_df = train_df.reset_index().rename(columns={'index':'id'})
train_df

id  depth  carat  table     x     y     z  color_D  color_E  \
0          0   62.4   1.21   58.0  6.83  6.79  4.25        0        0   
1          1   63.0   0.32   57.0  4.35  4.38  2.75        0        0   
2          2   65.5   0.71   55.0  5.62  5.53  3.65        0        0   
3          3   63.8   0.41   56.0  4.68  4.72  3.00        1        0   
4          4   60.5   1.02   59.0  6.55  6.51  3.95        0        0   
...      ...    ...    ...    ...   ...   ...   ...      ...      ...   
40450  40450   62.7   1.34   57.0  7.10  7.04  4.43        0        0   
40451  40451   57.1   2.02   60.0  8.31  8.25  4.73        0        0   
40452  40452   62.7   1.01   56.0  6.37  6.42  4.01        0        0   
40453  40453   61.9   0.33   54.3  4.45  4.47  2.76        0        0   
40454  40454   62.0   1.24   58.0  6.83  6.88  4.25        0        0   

       color_F  ...  city_Kimberly  city_Las Vegas  city_London  \
0            0  ...              0               0            0   
1            0  ...              1               0            0   
2            0  ...              0               1            0   
3            0  ...              1               0            0   
4            0  ...              0               0            0   
...        ...  ...            ...             ...          ...   
40450        0  ...              0               0            0   
40451        1  ...              0               0            0   
40452        0  ...              1               0            0   
40453        0  ...              1               0            0   
40454        0  ...              0               0            1   

       city_Luxembourg  city_Madrid  city_New York City  city_Paris  \
0                    0            0                   0           0   
1                    0            0                   0           0   
2                    0            0                   0           0   
3                    0            0                   0           0   
4                    0            0                   0           0   
...                ...          ...                 ...         ...   
40450                0            0                   0           0   
40451                0            1                   0           0   
40452                0            0                   0           0   
40453                0            0                   0           0   
40454                0            0                   0           0   

       city_Surat  city_Tel Aviv  city_Zurich  
0               0              0            0  
1               0              0            0  
2               0              0            0  
3               0              0            0  
4               0              0            0  
...           ...            ...          ...  
40450           0              0            0  
40451           0              0            0  
40452           0              0            0  
40453           0              0            0  
40454           0              0            0  

[40455 rows x 40 columns]

In [257]:
target_df = train_dataframe[['price']]
target_df

price
0       4268
1        505
2       2686
3        738
4       4882
...      ...
40450  10070
40451  12615
40452   5457
40453    456
40454   6232

[40455 rows x 1 columns]

In [272]:
#Scaler train
scaler = StandardScaler()
scaled_train = scaler.fit_transform(train_df)
scaled_train

array([[-1.73200799,  0.45201864,  0.8670056 , ..., -0.37865286,
        -0.25692004, -0.25648242],
       [-1.73192237,  0.8710986 , -1.00455749, ..., -0.37865286,
        -0.25692004, -0.25648242],
       [-1.73183674,  2.61726508, -0.18443434, ..., -0.37865286,
        -0.25692004, -0.25648242],
       ...,
       [ 1.73183674,  0.66155862,  0.44642962, ..., -0.37865286,
        -0.25692004, -0.25648242],
       [ 1.73192237,  0.10278535, -0.98352869, ..., -0.37865286,
        -0.25692004, -0.25648242],
       [ 1.73200799,  0.172632  ,  0.93009199, ..., -0.37865286,
        -0.25692004, -0.25648242]])

In [273]:
#Scaler train
scaler = StandardScaler()
scaled_test = scaler.fit_transform(test_df)
scaled_test

array([[-1.73192237, -0.01841187,  0.66950043, ..., -0.37518853,
        -0.2557701 , -0.26805668],
       [-1.73166548,  0.85507765, -0.51495701, ...,  2.66532669,
        -0.2557701 , -0.26805668],
       [-1.7314086 ,  1.64334867,  0.3211306 , ..., -0.37518853,
        -0.2557701 , -0.26805668],
       ...,
       [ 1.7314086 , -0.21015347, -0.09691321, ..., -0.37518853,
         3.9097611 , -0.26805668],
       [ 1.73166548, -0.21015347, -2.04778429, ...,  2.66532669,
        -0.2557701 , -0.26805668],
       [ 1.73192237, -0.84929214,  0.46047853, ..., -0.37518853,
        -0.2557701 , -0.26805668]])

In [274]:
model = LinearRegression()
model.fit(scaled_train, target_df)

LinearRegression()

In [275]:
X_test= scaler.fit_transform(scaled_test)
y_hat = model.predict(X_test).clip(0,30000) #esta es la predicción. es un array de numpy

In [280]:
y_hat.shape

(13485, 1)

In [281]:
y_hat.flatten()

array([0., 0., 0., ..., 0., 0., 0.])

In [282]:
submission = pd.DataFrame({'id': test_df['id'], 'price': y_hat.flatten()}) #convertimos a dataframe y le damos forma
submission.to_csv('submission.csv', index=False)